### ISSUE TITLE
package都不传上来，我install个鬼，糟老头子坏得很 ！！

### ISSUE THREAD

**Issue by TomLeel** [utadarei/TopSportsRealTimeMonitoring#1]
![image](https://user-images.githubusercontent.com/24224985/64098568-cd537580-cd99-11e9-8503-357fb794466d.png)

**Comment by utadarei** [comment]
之前用的jQuery写的，用的html引入js的方法，然后改用es 6 class的方式去整，暂时没把坑填完，有空再弄

**Comment by utadarei** [comment]
todo
